doctrine:
    dbal:
        dbname:               '%env(resolve:DB_NAME)%'
        host:                 '%env(resolve:DB_HOST)%'
        user:                 '%env(resolve:DB_USER)%'
        password:             '%env(resolve:DB_PASSWORD)%'
        driver:               'pdo_pgsql'
        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        server_version: '12'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
