@fixtures
Feature:
  We need to make sure to not get any autogenerated queries and mutations that have not been
  checked for security issues. This can happen if we create a new entity.

  Scenario: The graphql schema should only contain allowed queries and mutations
    When I use GraphQL introspection to load query, mutation and entity types of the schema
    Then the schema should only contain the allowed queries:
      | node      |
      | material  |
      | materials |
      | inflow    |
      | inflows   |
      | outflow   |
      | outflows  |

    Then the schema should only contain the allowed mutations:
      | createMaterial            |
      | updateMaterial            |
      | createInflow              |
      | updateInflow              |
      | deleteInflow              |
      | createOutflow             |
      | updateOutflow             |
      | customDeleteOutflow       |
      | approveReservationOutflow |
      | pickedUpReservationOutflow |
      | uploadMediaObject         |
      | updateMediaObject         |
      | deleteMediaObject         |
